version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - qfumbled
    assignees:
      - qfumbled
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: nix
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - qfumbled
    assignees:
      - qfumbled
    commit-message:
      prefix: chore
      include: scope
