version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "05:00" # 5:00 AM in New York time
      timezone: "America/New_York"
    reviewers:
      - qfumbled
    assignees:
      - qfumbled
    commit-message:
      prefix: chore
      include: scope
