# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "vmd" "ahci" "nvme" "usbhid"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/7f84cadc-3507-4a39-a23f-70a9754a50e9";
    fsType = "ext4";
  };

  fileSystems."/var/lib/nixos" = {
    device = "/persist/var/lib/nixos";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/var/log" = {
    device = "/persist/var/log";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/etc/nixos" = {
    device = "/persist/etc/nixos";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/persist/passwords" = {
    device = "/persist/persist/passwords";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/etc/secureboot" = {
    device = "/persist/etc/secureboot";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F6A7-51C6";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/var/db/sudo" = {
    device = "/persist/var/db/sudo";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/var/lib/systemd/coredump" = {
    device = "/persist/var/lib/systemd/coredump";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/var/lib/tailscale" = {
    device = "/persist/var/lib/tailscale";
    fsType = "none";
    options = ["bind"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
