{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.opt.lanzaboote;
in {
  options.opt.lanzaboote = {
    enable = lib.mkEnableOption "Enable Lanzaboote + sbctl Secure Boot integration";
    pkiBundle = lib.mkOption {
      type = lib.types.path;
      default = "/var/lib/sbctl";
      description = "Path to PKI bundle for Lanzaboote (usually generated by sbctl)";
    };
  };

  # Make sure lanzaboote is always enabled by default
  config = {
    boot = {
      lanzaboote = {
        enable = true;  # Default to true
        pkiBundle = cfg.pkiBundle;
      };

      loader.systemd-boot.enable = lib.mkForce false;
    };

    environment.systemPackages = [pkgs.sbctl];
  };
}
