name: Validate Nix Flake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *" # Run daily at 12am EDT
  push:
    paths:
      - "**.nix"
      - "**.lock"
      - ".github/workflows/check.yml"

jobs:
  check-flake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty

      - name: Check Flake
        run: nix flake check --accept-flake-config --extra-experimental-features 'nix-command flakes pipe-operators'
