name: Build NixOS Configurations

on:
  workflow_dispatch:
  push:
    paths:
      - "**.nix"
      - "flake.lock"
      - ".github/workflows/ci.yml"

jobs:
  build-config:
    strategy:
      matrix:
        include:
          - hostName: desktop
            nixosCfgKey: desktop
            os-label: ubuntu-latest
          - hostName: laptop
            nixosCfgKey: laptop
            os-label: ubuntu-latest
      fail-fast: false

    name: Build ${{ matrix.hostName }}
    runs-on: ${{ matrix.os-label }}

    steps:
      - name: Maximize disk space
        uses: easimon/maximize-build-space@master
        with:
          build-mount-path: /nix
          root-reserve-mb: 1024
          remove-dotnet: true
          remove-android: true
          remove-haskell: true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30

      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 21474836480
          purge: false

      - name: Build NixOS Configuration
        run: nix build .#nixosConfigurations.${{ matrix.nixosCfgKey }}.config.system.build.toplevel
