name: Bump Flake Inputs

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at 00:00 UTC

jobs:
  update-lockfile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # Required for pushing + PR

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty

      - name: Update Lockfile
        uses: DeterminateSystems/update-flake-lock@main
        id: update
        with:
          pr-title: ":package: (flake): update"
          commit-msg: ":package: (flake): update"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Changes
        if: ${{ steps.update.outputs.pull-request-number != '' }}
        run: gh pr merge ${{ steps.update.outputs.pull-request-number }} --squash --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
